### ISSUE TITLE
[FEAT] - Optional User Parameter

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/weLoveHacktoberfest#412]
### What feature would you like to see?

The `/faq` command should be given a `user` option. This needs to be **not required**.

If the command is passed a value for this parameter, the faq response should be modified to include a `content` value of `Hey <@!${user.id}, this should answer your question`.

**Comment by danicunhac** [comment]
Hey @naomi-lgbt! I'd love to take this one. Also, are there any instructions on how to setup the dev environment?

**Comment by naomi-lgbt** [comment]
Refer to https://docs.nhcarrigan.com/#/we-love-hacktoberfest/contributing and https://docs.nhcarrigan.com/#/contributing

**Comment by danicunhac** [comment]
Should there be a description for this one, created by the collaborators?
