### ISSUE TITLE
[FEAT] - Automoderation of project-sharing

### ISSUE THREAD

**Issue by MattIPv4** [nhcarrigan/weLoveHacktoberfest#413]
### What feature would you like to see?

👋 Curious what y'all think about adding this into the scope of the bot, but it'd be really useful to have something that automoderates the project-sharing channel in the Hacktoberfest Discord server.

Ideally, it would remove any message that doesn't contain a link to a GitHub/GitLab repository (or an issue within a repository), and DMs the user letting them know that their message was removed because of that.

The DM should explain that the channel is for sharing projects that are looking for help, and that for other conversations channels such as general should be used.

### Additional information

I'll need to grant the bot powers to delete messages in this channel if this feature does get approved. The bot should check it has that permission in the channel, and cleanly handle the situation if it doesn't.

**Comment by MattIPv4** [comment]
(If this does go through, I think a future step would be to enable similar automoderation of post-sharing and event-sharing, just removing any posts that don't contain any link at all. Might be worth keeping that in mind when implementing this, so that logic could be written in an abstracted way that could be reused for this down the road)

**Comment by naomi-lgbt** [comment]
`/http(s)?\:\/\/(www\.)?git(hub|lab)\.com/.test(content)`

Not a bad idea. Gonna label this for contribution - heading out the door but will write up a better spec when I'm home.

**Comment by MattIPv4** [comment]
`/\bhttps?:\/\/(www\.)?git(hub|lab)\.com\/[^\/]+\/[^\/]+((\/-)?\/issues\/\d+)?\b/.test(content)` should allow for project links, or links directly to issues

**Comment by Tenotea** [comment]
Hi @naomi-lgbt, can you assign this to me? I'd like to work on this.

**Comment by Yashsomalkar** [comment]
Heya, @naomi-lgbt, I am a budding contributor; this feature looks fantastic to me; I would love to contribute :)
And If this is already assigned, is there anything else I can contribute to 👀?

**Comment by naomi-lgbt** [comment]
Hi friends,

Thank you for your interest in contributing to our project. However, given the nature of this feature, and the need to work closely with the HF moderation team to ensure implementation is correct, we've decided to scope this as a staff only issue.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.naomi.lgbt)
