### ISSUE TITLE
[BUG] - Fix interaction response if tag is not found

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/weLoveHacktoberfest#415]
### What bug did you encounter?

The bot is set to respond with a reply if an invalid tag is passed.

However, because it is `interaction.reply` and not `interaction.editReply`, the bot throws an "interaction has already been deferred" error.

https://github.com/nhcarrigan/weLoveHacktoberfest/blob/391d4186c2d90460588512baa9cac05d5c553b05/src/commands/faq.ts#L27

### What did you expect to happen?

The bot should properly send the invalid tag response.

**Comment by botatooo** [comment]
I've finished this one @ #416
