### ISSUE TITLE
[BUG] - checkProject allows https://github.com/orgs/org-name-here

### ISSUE THREAD

**Issue by MattIPv4** [nhcarrigan/weLoveHacktoberfest#717]
### What bug did you encounter?

Reported by a user in the Discord server, you can get around the bot's auto-moderation of the projects channel and post a GitHub organisation rather than a project by using `https://github.com/orgs/org-name-here` rather than `https://github.com/org-name-here`, as the bot will treat that as an organisation named `orgs` and a repository named `org-name-here`.

### What did you expect to happen?

https://github.com/nhcarrigan/weLoveHacktoberfest/blob/main/src/modules/checkProject.ts should be updated such that `orgs` is not permitted as an org name. I suspect it'll be easier to add a secondary check after the initial regex pattern, rather than trying to block this in the existing regex pattern.

**Comment by postmodern** [comment]
Not that `https://github.com/orgs/org-name-here` only properly redirects for actual GitHub Orgs. t will return 404 if you try to use a GitHub username in the URL: https://github.com/orgs/ronin-rb vs. https://github.com/orgs/postmodern

**Comment by ElectroBoy404NotFound** [comment]
> Not that `https://github.com/orgs/org-name-here` only properly redirects for actual GitHub Orgs. t will return 404 if you try to use a GitHub username in the URL: https://github.com/orgs/ronin-rb vs. https://github.com/orgs/postmodern

Well, That's what he mentions in the issue. `...of the projects channel and post a **GitHub organisation** rather than a project by using...`
