### ISSUE TITLE
[CHORE] - Add new sponsors

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/weLoveHacktoberfest#723]
### What work needs to be performed?

This year's sponsors need to be loaded into the config.

We should add [config objects](https://github.com/nhcarrigan/weLoveHacktoberfest/blob/main/src/data/loveData.ts) for:

- Illa Cloud
- Amplication
- Runme
- OpenSauced
- MLH
- Hugging Face

**Comment by probablyArth** [comment]
I'd like to get assigned 🤚

**Comment by naomi-lgbt** [comment]
All yours!

**Comment by probablyArth** [comment]
should I do it after 1st october?

**Comment by naomi-lgbt** [comment]
if you want it to count for hacktoberfest, yes.

**Comment by rudravashishtha** [comment]
I have linked a pull request. @naomi-lgbt 
Will you merge this after 1st October?

**Comment by naomi-lgbt** [comment]
Pull requests opened prior to October 1st will **not** count toward Hacktoberfest, regardless of when they are merged.

**Comment by rudravashishtha** [comment]
I guess then its your call.
You can merge it anyways if you want.

**Comment by probablyArth** [comment]
okay Ill raise the PR after 1st Oct

**Comment by rudravashishtha** [comment]
> Pull requests opened prior to October 1st will **not** count toward Hacktoberfest, regardless of when they are merged.

Do you want me to close this from my end then?
