### ISSUE TITLE
[BUG] - Custom  text markdown links not recognised in #project-sharing

### ISSUE THREAD

**Issue by LunarWatcher** [nhcarrigan/weLoveHacktoberfest#724]
### What bug did you encounter?

The bot currently doesn't recognise repository links for project-sharing if they're posted in `[markdown format](https://example.com)`. See https://discord.com/channels/720788516837261322/735506302784110652/1150908218457993286

### What did you expect to happen?

I'd expect the links to be recognised. Markdown links are valid on Discord now

**Comment by MattIPv4** [comment]
The easiest fix is probably to update `boundary` to allow `(` and `)`: https://github.com/nhcarrigan/weLoveHacktoberfest/blob/2905287ff607533f9fd589af3fe571126a153fc6/src/config/ProjectRegex.ts#L1

I would think this is probably a good opportunity to split it into `boundaryStart` and `boundaryEnd`, `(?:^|\(|[ \t\n])` and `(?:$|\)|[ \t\n])` respectively.
