### ISSUE TITLE
[FEAT] - Command to generate query URLs

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/weLoveHacktoberfest#740]
### What feature would you like to see?

We should add a `/search` command which accepts:

- A VCS param, set to choices between GitHub and GitLab
- A language param, which is string

The command should return a query string using the VCS' search syntax. For example, `/search vsc:GitHub lang:TypeScript` should return `https://github.com/search?q=topic%3Ahacktoberfest%20language%3Atypescript&type=repositories` - note the inclusion of the hacktoberfest topic.

**Comment by Vyvy-vi** [comment]
I'd like to work on this

**Comment by naomi-lgbt** [comment]
Go for it~!
