### ISSUE TITLE
[FEAT] - Allow issues index links

### ISSUE THREAD

**Issue by MattIPv4** [nhcarrigan/weLoveHacktoberfest#764]
### What feature would you like to see?

The project-sharing filtering allows for a repository URL to be shared, or a specific issue within a repository.

This should be updated to allow the issues index page to also be shared. Bonus points for allowing query parameters on it (so folks could deep-link to good-first-issue labels etc.).

### Additional information

Example links:

- https://github.com/nhcarrigan/weLoveHacktoberfest/issues
- https://github.com/nhcarrigan/weLoveHacktoberfest/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by naomi-lgbt** [comment]
A PR which resolves this issue should also update the test cases for both the regex and the owner/repo parser.
