### ISSUE TITLE
[CHORE] - Add tag about purging github images

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/weLoveHacktoberfest#782]
### What work needs to be performed?

We're getting a lot of questions about why Holopin boards embedded in a GitHub profile don't update.

GitHub caches images aggressively. We should add a tag explaining this, and link to the docs for purging the CDN cache: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls#removing-an-image-from-camos-cache

**Comment by ieahleen** [comment]
can I work on this?

**Comment by naomi-lgbt** [comment]
Go for it!
